#!/usr/bin/env bash
# ArcanisScripts Environment Configuration
# Usage: ./config.sh [action] [options]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

ACTION="${1:-list}"
FORCE=false
VERBOSE=false
VAR_NAME=""
VAR_VALUE=""
ENVIRONMENT="development"
FILE=".env"

show_help() {
    cat << EOF
ArcanisScripts Environment Configuration

Usage: ./config.sh [action] [options]

Actions:
    init         Initialize .env file from template
    set          Set an environment variable
    get          Get an environment variable value
    list         List all environment variables (default)
    validate     Validate required environment variables
    export       Export environment variables to file
    import       Import environment variables from file
    help         Show this help message

Options:
    -f, --force           Skip confirmation prompts
    -v, --verbose         Enable verbose output
    -n, --name            Variable name
    -V, --value           Variable value
    -e, --environment     Target environment (development, staging, production)
    -F, --file            Environment file path (default: .env)

Examples:
    ./config.sh init
    ./config.sh set --name "API_KEY" --value "abc123"
    ./config.sh get --name "DATABASE_URL"
    ./config.sh list
    ./config.sh validate
    ./config.sh export --file ".env.production"
    ./config.sh import --file ".env.example"
EOF
}

init_environment() {
    log_info "Initializing environment configuration..."
    
    local root
    root=$(get_project_root)
    local env_file="$root/$FILE"
    
    if [ -f "$env_file" ] && [ "$FORCE" = false ]; then
        if ! confirm_action "$FILE already exists. Overwrite?"; then
            return 0
        fi
    fi
    
    # Create .env file with common variables
    cat > "$env_file" << 'EOF'
# ArcanisScripts Environment Configuration
# Generated by ArcanisScripts

# Application
APP_NAME=my-app
APP_VERSION=1.0.0
APP_ENV=development
APP_DEBUG=false
APP_PORT=3000

# Database
DATABASE_URL=postgresql://user:password@localhost:5432/dbname
DATABASE_POOL_SIZE=10

# Redis
REDIS_URL=redis://localhost:6379

# API Keys
API_KEY=
API_SECRET=

# Authentication
JWT_SECRET=
JWT_EXPIRATION=24h

# Logging
LOG_LEVEL=info
LOG_FILE=logs/app.log

# Services
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=us-east-1
EOF
    
    # Create .env.example (without sensitive values)
    sed -E 's/(PASSWORD|SECRET|KEY|TOKEN)=.*/\1=your-\L\1/' "$env_file" > "$root/.env.example"
    
    # Create .gitignore entry if not exists
    local gitignore="$root/.gitignore"
    if [ -f "$gitignore" ]; then
        if ! grep -q "^\.env$" "$gitignore"; then
            echo -e "\n.env\n.env.local\n.env.*.local" >> "$gitignore"
        fi
    fi
    
    log_success "Environment files created:"
    log_info "  - $FILE (with values)"
    log_info "  - .env.example (template)"
}

set_environment_variable() {
    if [ -z "$VAR_NAME" ]; then
        log_error "Variable name is required"
        return 1
    fi
    
    local root
    root=$(get_project_root)
    local env_file="$root/$FILE"
    
    if [ ! -f "$env_file" ]; then
        log_error "Environment file not found. Run 'init' first."
        return 1
    fi
    
    # Check if variable exists
    if grep -q "^$VAR_NAME=" "$env_file"; then
        # Update existing variable
        sed -i.bak "s/^$VAR_NAME=.*/$VAR_NAME=$VAR_VALUE/" "$env_file"
        rm -f "$env_file.bak"
    else
        # Add new variable
        echo "$VAR_NAME=$VAR_VALUE" >> "$env_file"
    fi
    
    log_success "Set $VAR_NAME=$VAR_VALUE"
}

get_environment_variable() {
    if [ -z "$VAR_NAME" ]; then
        log_error "Variable name is required"
        return 1
    fi
    
    local root
    root=$(get_project_root)
    local env_file="$root/$FILE"
    
    if [ ! -f "$env_file" ]; then
        log_error "Environment file not found"
        return 1
    fi
    
    local value
    value=$(grep "^$VAR_NAME=" "$env_file" | cut -d'=' -f2-)
    
    if [ -n "$value" ]; then
        echo "$value"
    else
        log_warning "Variable '$VAR_NAME' not found"
        return 1
    fi
}

list_environment_variables() {
    log_info "Environment variables ($FILE):"
    
    local root
    root=$(get_project_root)
    local env_file="$root/$FILE"
    
    if [ ! -f "$env_file" ]; then
        log_error "Environment file not found"
        return 1
    fi
    
    echo ""
    printf "%-30s %s\n" "Variable" "Value"
    printf "%-30s %s\n" "----------------------------------------" "----------------------------------------"
    
    while IFS='=' read -r name value; do
        # Skip comments and empty lines
        [[ "$name" =~ ^[[:space:]]*# ]] && continue
        [[ -z "$name" ]] && continue
        
        # Trim whitespace
        name=$(echo "$name" | xargs)
        
        # Mask sensitive values
        if [[ "$name" =~ (SECRET|PASSWORD|KEY|TOKEN) ]]; then
            value="***"
        fi
        
        # Truncate long values
        if [ ${#value} -gt 30 ]; then
            value="${value:0:27}..."
        fi
        
        printf "%-30s %s\n" "$name" "$value"
    done < "$env_file"
}

validate_environment_variables() {
    log_info "Validating environment variables..."
    
    local root
    root=$(get_project_root)
    local env_file="$root/$FILE"
    
    if [ ! -f "$env_file" ]; then
        log_error "Environment file not found"
        return 1
    fi
    
    local required_vars=(
        "APP_NAME"
        "APP_ENV"
        "DATABASE_URL"
        "API_KEY"
    )
    
    local missing=()
    
    for var in "${required_vars[@]}"; do
        if ! grep -q "^$var=.+" "$env_file"; then
            missing+=("$var")
        fi
    done
    
    if [ ${#missing[@]} -eq 0 ]; then
        log_success "All required variables are set"
    else
        log_error "Missing required variables:"
        for var in "${missing[@]}"; do
            log_error "  - $var"
        done
        return 1
    fi
}

export_environment_variables() {
    log_info "Exporting environment variables..."
    
    local root
    root=$(get_project_root)
    local source_file="$root/$FILE"
    local dest_file="$root/$FILE"
    
    if [ ! -f "$source_file" ]; then
        log_error "Source environment file not found"
        return 1
    fi
    
    cp "$source_file" "$dest_file"
    
    log_success "Exported to: $FILE"
}

import_environment_variables() {
    log_info "Importing environment variables..."
    
    local root
    root=$(get_project_root)
    local source_file="$root/$FILE"
    local dest_file="$root/$FILE"
    
    if [ ! -f "$source_file" ]; then
        log_error "Source file not found: $FILE"
        return 1
    fi
    
    if [ -f "$dest_file" ] && [ "$FORCE" = false ]; then
        if ! confirm_action "This will overwrite existing $FILE. Continue?"; then
            return 0
        fi
    fi
    
    cp "$source_file" "$dest_file"
    
    log_success "Imported from: $FILE"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--force)
            FORCE=true
            shift
            ;;
        -v|--verbose)
            VERBOSE=true
            shift
            ;;
        -n|--name)
            VAR_NAME="$2"
            shift 2
            ;;
        -V|--value)
            VAR_VALUE="$2"
            shift 2
            ;;
        -e|--environment)
            ENVIRONMENT="$2"
            shift 2
            ;;
        -F|--file)
            FILE="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            ACTION="$1"
            shift
            ;;
    esac
done

# Main execution
case $ACTION in
    init)
        init_environment
        ;;
    set)
        set_environment_variable
        ;;
    get)
        get_environment_variable
        ;;
    list)
        list_environment_variables
        ;;
    validate)
        validate_environment_variables
        ;;
    export)
        export_environment_variables
        ;;
    import)
        import_environment_variables
        ;;
    help)
        show_help
        ;;
    *)
        log_error "Unknown action: $ACTION"
        show_help
        exit 1
        ;;
esac
