import {
  Program, FunctionDecl, ParamDecl, VarDecl, BlockStmt, ExprStmt,
  IfStmt, WhileStmt, ReturnStmt, BinaryExpr, UnaryExpr, CallExpr,
  Identifier, IntLiteral, FloatLiteral, StringLiteral, BoolLiteral,
  UnitLiteral, GroupExpr, Stmt, Expr,
} from '../parser/ast';
import { Type, TypeKind, BinaryOp, UnaryOp } from '../types';
import { DebugInfoBuilder } from '../debug';

export interface CodeGenTarget {
  generate(program: Program, debugInfo?: DebugInfoBuilder): string;
  name(): string;
}

export class JavaScriptCodeGen implements CodeGenTarget {
  private indentLevel = 0;
  private sourceId: string;
  private debugInfo?: DebugInfoBuilder;
  private varCounter = 0;

  constructor(sourceId: string = '<stdin>') {
    this.sourceId = sourceId;
  }

  name(): string {
    return 'javascript';
  }

  generate(program: Program, debugInfo?: DebugInfoBuilder): string {
    this.debugInfo = debugInfo;
    this.indentLevel = 0;
    this.varCounter = 0;
    const parts: string[] = [];

    // Emit runtime preamble
    parts.push(this.generatePreamble());

    // Generate code for each function
    for (const fn of program.functions) {
      parts.push(this.generateFunction(fn));
    }

    // Generate code for top-level statements
    for (const stmt of program.statements) {
      parts.push(this.generateStmt(stmt));
    }

    return parts.join('\n');
  }

  private generatePreamble(): string {
    return [
      '// Generated by ArcanisCompiler',
      `// Source: ${this.sourceId}`,
      '',
      `const __arcanis = (typeof globalThis !== 'undefined' ? globalThis : (typeof window !== 'undefined' ? window : {}));`,
      '',
      'function __readInt() {',
      '  const result = parseInt(__readString(), 10);',
      '  return isNaN(result) ? 0 : result;',
      '}',
      '',
      'function __readString() {',
      '  if (typeof prompt !== "undefined") {',
      '    return prompt("") || "";',
      '  }',
      '  return "";',
      '}',
      '',
    ].join('\n');
  }

  private generateFunction(fn: FunctionDecl): string {
    const params = fn.params.map((p) => this.generateParam(p)).join(', ');
    let code = `function ${fn.name}(${params}) {\n`;

    this.indentLevel++;
    const bodyCode = this.generateBlockBody(fn.body);
    code += bodyCode;
    this.indentLevel--;

    code += '}\n';
    return code;
  }

  private generateParam(param: ParamDecl): string {
    return param.name;
  }

  private generateBlockBody(block: BlockStmt): string {
    const parts: string[] = [];
    for (const stmt of block.statements) {
      parts.push(this.generateStmt(stmt));
    }
    return parts.join('\n');
  }

  private generateStmt(stmt: Stmt): string {
    if (stmt instanceof VarDecl) {
      return this.generateVarDecl(stmt);
    }
    if (stmt instanceof BlockStmt) {
      const body = this.generateBlockBody(stmt);
      return `{\n${body}\n${this.indent()}}`;
    }
    if (stmt instanceof ExprStmt) {
      return `${this.indent()}${this.generateExpr(stmt.expression)};`;
    }
    if (stmt instanceof IfStmt) {
      return this.generateIfStmt(stmt);
    }
    if (stmt instanceof WhileStmt) {
      return this.generateWhileStmt(stmt);
    }
    if (stmt instanceof ReturnStmt) {
      if (stmt.value) {
        return `${this.indent()}return ${this.generateExpr(stmt.value)};`;
      }
      return `${this.indent()}return;`;
    }
    return '';
  }

  private generateVarDecl(stmt: VarDecl): string {
    const name = stmt.name;
    if (stmt.initializer) {
      return `${this.indent()}let ${name} = ${this.generateExpr(stmt.initializer)};`;
    }
    // Default initialization based on type
    if (stmt.varType.kind === TypeKind.Int) {
      return `${this.indent()}let ${name} = 0;`;
    }
    if (stmt.varType.kind === TypeKind.Float) {
      return `${this.indent()}let ${name} = 0.0;`;
    }
    if (stmt.varType.kind === TypeKind.Bool) {
      return `${this.indent()}let ${name} = false;`;
    }
    if (stmt.varType.kind === TypeKind.String) {
      return `${this.indent()}let ${name} = "";`;
    }
    return `${this.indent()}let ${name} = null;`;
  }

  private generateIfStmt(stmt: IfStmt): string {
    let code = `${this.indent()}if (${this.generateExpr(stmt.condition)}) {\n`;
    this.indentLevel++;
    code += this.generateStmtCode(stmt.thenBranch);
    this.indentLevel--;
    code += `${this.indent()}}`;

    if (stmt.elseBranch) {
      code += ` else {\n`;
      this.indentLevel++;
      code += this.generateStmtCode(stmt.elseBranch);
      this.indentLevel--;
      code += `${this.indent()}}`;
    }

    return code;
  }

  private generateWhileStmt(stmt: WhileStmt): string {
    let code = `${this.indent()}while (${this.generateExpr(stmt.condition)}) {\n`;
    this.indentLevel++;
    code += this.generateStmtCode(stmt.body);
    this.indentLevel--;
    code += `${this.indent()}}`;
    return code;
  }

  private generateStmtCode(stmt: Stmt): string {
    if (stmt instanceof BlockStmt) {
      return this.generateBlockBody(stmt);
    }
    return this.generateStmt(stmt);
  }

  private generateExpr(expr: Expr): string {
    if (expr instanceof IntLiteral) {
      return expr.value.toString();
    }
    if (expr instanceof FloatLiteral) {
      return expr.value.toString();
    }
    if (expr instanceof StringLiteral) {
      return JSON.stringify(expr.value);
    }
    if (expr instanceof BoolLiteral) {
      return expr.value ? 'true' : 'false';
    }
    if (expr instanceof UnitLiteral) {
      return 'null';
    }
    if (expr instanceof Identifier) {
      return expr.name;
    }
    if (expr instanceof GroupExpr) {
      return `(${this.generateExpr(expr.expression)})`;
    }
    if (expr instanceof UnaryExpr) {
      return this.generateUnary(expr);
    }
    if (expr instanceof BinaryExpr) {
      return this.generateBinary(expr);
    }
    if (expr instanceof CallExpr) {
      return this.generateCall(expr);
    }
    return 'null';
  }

  private generateUnary(expr: UnaryExpr): string {
    const operand = this.generateExpr(expr.operand);
    if (expr.op === UnaryOp.Negate) return `-${operand}`;
    if (expr.op === UnaryOp.Not) return `!${operand}`;
    return operand;
  }

  private generateBinary(expr: BinaryExpr): string {
    const left = this.generateExpr(expr.left);
    const right = this.generateExpr(expr.right);

    switch (expr.op) {
      case BinaryOp.Add: return `(${left} + ${right})`;
      case BinaryOp.Subtract: return `(${left} - ${right})`;
      case BinaryOp.Multiply: return `(${left} * ${right})`;
      case BinaryOp.Divide: return `(${left} / ${right})`;
      case BinaryOp.Modulo: return `(${left} % ${right})`;
      case BinaryOp.Equal: return `(${left} === ${right})`;
      case BinaryOp.NotEqual: return `(${left} !== ${right})`;
      case BinaryOp.LessThan: return `(${left} < ${right})`;
      case BinaryOp.GreaterThan: return `(${left} > ${right})`;
      case BinaryOp.LessEqual: return `(${left} <= ${right})`;
      case BinaryOp.GreaterEqual: return `(${left} >= ${right})`;
      case BinaryOp.And: return `(${left} && ${right})`;
      case BinaryOp.Or: return `(${left} || ${right})`;
      case BinaryOp.Assign: return `(${left} = ${right})`;
      default: return 'null';
    }
  }

  private generateCall(expr: CallExpr): string {
    const callee = this.generateExpr(expr.callee);
    const args = expr.args.map((a) => this.generateExpr(a)).join(', ');

    // Map built-in functions
    if (expr.callee instanceof Identifier) {
      switch (expr.callee.name) {
        case 'print':
          return `process.stdout.write(String(${expr.args.map((a) => this.generateExpr(a)).join(', ')}))`;
        case 'println':
          return `console.log(${expr.args.map((a) => this.generateExpr(a)).join(', ')})`;
        case 'printlnInt':
          return `console.log(${expr.args.map((a) => this.generateExpr(a)).join(', ')})`;
        case 'readInt':
          return `__readInt()`;
        case 'readString':
          return `__readString()`;
        case 'intToString':
          return `String(${expr.args.map((a) => this.generateExpr(a)).join(', ')})`;
        case 'floatToString':
          return `String(${expr.args.map((a) => this.generateExpr(a)).join(', ')})`;
      }
    }

    return `${callee}(${args})`;
  }

  private indent(): string {
    return '  '.repeat(this.indentLevel);
  }
}
