import { readFileSync, readdirSync, statSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = join(__dirname, 'src');

function generateTypes(dir, prefix = '') {
  const results = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      results.push(...generateTypes(fullPath, `${prefix}${entry}/`));
    } else if (entry.endsWith('.ts') && !entry.endsWith('.test.ts')) {
      const content = readFileSync(fullPath, 'utf-8');
      const exports = content.match(/export\s+(function|const|class|interface|type)\s+(\w+)/g) || [];
      exports.forEach((exp) => {
        const name = exp.replace(/export\s+(function|const|class|interface|type)\s+/, '');
        results.push(`export { ${name} } from './${prefix}${entry.replace('.ts', '')}';`);
      });
    }
  }
  return results;
}

console.log('Type definitions are generated by tsc.');
